### ISSUE TITLE
File list updates on deleted files/folders

### ISSUE THREAD

**Issue by psiha** [damoncourtney/installjammer#20]
Please add the option to make the files/file groups/folder automatically rescan and update themselves even when files are removed/deleted, not just added (currently the build will fail if a file was externally deleted...which is a common case when the files and folders are automatcially updated through source control).

**Comment by damoncourtney** [comment]
The file list automatically updates when you refresh it or when you build.  By default, InstallJammer tracks all files that you add so that deleted files will cause an error when attempting to build without them.  This is actually done on purpose to warn you when your installation has changed from the original project.

Under Application Information -> Project Preferences are two options: Build Failure Action and Command Line Failure Action.  You can set both of these to Continue without including missing files, and your installer will build without the missing files.

You can also add a directory to your installer that does not actually remember anything underneath it.  Meaning that you only add the single, toplevel directory to the project, and the contents of that directory will always be dynamically added when you build.  Take a look at the Save Files option of each file group or directory.

In 1.3, these options have been renamed to File Save Method, and there is a global option under Application Information -> Project Preferences to set it globally for the entire project.

**Comment by damoncourtney** [comment]
I think the builder does what you need here unless there is something I missed.  Closing this.
