### ISSUE TITLE
TAR truncating long file names

### ISSUE THREAD

**Issue by rogerB** [damoncourtney/installjammer#27]
When InstallJammer builds the Tar Archive platform, it is truncating the file names of files with long paths/names

E.G.
Name: ==> BBBB-CCC-DD-DATASET1_EEE_YYYYMMDDHHMMSSZ_YYYYMMDDHHMMSSZ_ee00000000000000Z_1_FFFF_GGG_HHHH_III.xml
Location: ==> Q:/myName_my_view_buildNumber_b1.0/AAA/data/extra 
Install Location: ==> <%InstallDir%>/AAA/data/extra/BBBB-CCC-DD-DATASET1_EEE_YYYYMMDDHHMMSSZ_YYYYMMDDHHMMSSZ_ee00000000000000Z_1_FFFF_GGG_HHHH_III.xml

Is truncated at:
AAA/data/extra/BBBB-CCC-DD-DATASET

And

Name: ==> CCCCCC-DDD-EE_FFF_YYYYMMDDHHMMSSZ_YYYYMMDDHHMMSSZ_ee00000000000000Z_1_GGGG_HHH_IIII_JJJ.xml
Location: ==> Q:/RogerB_my_view_buildNumber_b1.5/AAA/data/aaaTables 
Install Location: ==> <%InstallDir%>/AAA/data/aaaTables/CCCCCC-DDD-EE_FFF_YYYYMMDDHHMMSSZ_YYYYMMDDHHMMSSZ_ee00000000000000Z_1_GGGG_HHH_IIII_JJJ.xml

Is truncated at:
AAA/data/aaaTables/CCCCCC-DDD-EE_FFF_YYYYMMDDHHMMSSZ_YYYYMMDD

**Comment by damoncourtney** [comment]
Took a look at this the other night, and there is definitely something wrong in the tar code, but I'm not sure what it is yet.  The other problem is that, given the examples you use here, it's not going to work anyway.  The tar code I have doesn't use the latest formats, which are decidedly more complex than the simple tar headers of old.  The filenames you're using just won't fit in the old format.

Have you thought about using a .zip file instead of tar?  It's not as fashionable on UNIX platforms, but .zip is by far the preferred format on Windows.

**Comment by damoncourtney** [comment]
I fixed the bug with truncating filenames, so you should be good now.  The tar code will now dump an error if the filename you're using is actually too long to fit.  Just remember that tar is basically going to split your file path at the / character.

The actual path can be up to 155 characters, but the single name of the file itself can only be 100.  That's the limitation you're dealing with.  The code is correct now at least. 0-]
