### ISSUE TITLE
Both Linux and Windows show "bad central file record" error

### ISSUE THREAD

**Issue by dthoms** [damoncourtney/installjammer#49]
This happens as soon as I try to execute the built installer.  Up to that point, no error or unusual things happen

**Comment by damoncourtney** [comment]
I discovered this as a bug in the build process.  The installkits were built properly with support for large installers, but my build system that packaged up the release failed to pick them up due to a bug.

So, I fixed the build system bug and reran the hourly build.  Please grab the latest 1.2 hourly snapshot and see if it fixes the bug.  If it does, I will make a 1.2.16 release next week to fix this error as well as a few small others people have reported.

**Comment by shortsightedsid** [comment]
Hi,

I actually came here to report the same issue on 1.2.15. I tried out the latest hourly snapshot on Ubuntu 10.04. The snapshot fixes my issue.

Thanks,
Sid

**Comment by damoncourtney** [comment]
Yeah.  I figured it out as soon as I looked at the dates on the binaries.  All from last May. 0-]

Thanks for reporting back.
