### ISSUE TITLE
UninstallPercentComplete does not update Uninstall Pane

### ISSUE THREAD

**Issue by ams001** [damoncourtney/installjammer#8]
I am using 1.2.14, latest snapshot.

I have added an Execute action for the Uninstall pane which updates UninstallPercentComplete but the progress bar does not update.  Well, it does, but only when the action has completed. 

To verify my theory I set up a sequence of Wait actions followed by SetVirtualText actions and the progress bar updated at the end of each action, but it does not update while the virtualtext is updated with the action.  

For example, the adding the ExecuteScript action:
for {set i 0} {$i<100} {incr i 1} {
  ::InstallAPI::SetVirtualText -virtualtext UninstallPercentComplete -value $i
  after 500
}

just causes a 50s delay without any progress bar update, and then jumps to 100%

**Comment by ams001** [comment]
FAOD, adding ::InstallJammer::UpdateWidgets into the loop still does not update the status bar.

**Comment by damoncourtney** [comment]
The problem is that your loop is blocking the event loop from processing events, so even though you've set the progress bar variable, the progress bar itself doesn't update unless the event loop is allowed to process events.  This doesn't happen in a loop where you maintain control of the program for a long period of time.

The UpdateWidgets call will actually do the update to the progress bar, but it still doesn't allow the event loop to process unless you tell it to.  Update widgets basically says, "Look for any changes in virtual text and redraw elements on the pane in accordance."  But it doesn't force an event loop update unless told to.

There are two answers here.  You can add the UpdateWidgets call like you've done and tell it to update like so:

::InstallJammer::UpdateWidgets -update 1

Or, you can set the variable itself as an auto-update variables.  Which, to be honest, should be done already.  The only variable that is auto-update by default is Status.  The thing that's good about this method is that it uses the standard APIs.  While UpdateWidgets is perfectly ok to use, it's not officially in the API, so it may change at some point without warning.  It's always best to use the APIs where you can.

Add this line just before your loop:

::InstallAPI::SetVirtualText -virtualtext UninstallPercentComplete -autoupdate 1

That should turn it on so that anytime you set the virtual text, it will automatically force a redraw and event loop update on the pane.  This SHOULD work, but it may not work completely in a loop like this because it effectively calls "update idletasks" instead of a hard update.  The idletasks may be enough, but we'll see. 0-]

**Comment by ams001** [comment]
Thanks.  Setting the autoupdate worked for my example script.  Unfortunately the example script detracted from the real problem, which is that the progress bar does not update when executing an external program during uninstall.  In fact, the example script was just an attempted workaround to this problem. 

The external program does output
:UninstallPercentComplete x:
where x=1 to 100 and I can confirm the virtual variable is updated because at the end of execution, the progress bar jumps to 100% (I have confirmed this through testing by adding a message box after the external program execution that outputs <%UninstallpercentComplete%> - and varied the final UninstallPercentComplete to confirm it is not left at 100).

FYI, I ran the above example script before calling the external program, so autoupdate was being set for UninstallPercentComplete, hoping to see the progress bar update 2x, but it only updated 1x (I restored it to 0 after execiting the above script).

Anyway, at least I now have a workaround, thanks to your help, for the real problem. I can now write a script that parses the output of the external program, matching 
:UninstallPercentComplete (\d+):$
and calling
::InstallAPI::SetVirtualText -virtualtext UninstallPercentComplete -value $1
to update the progress bar.  Obviously it would be best if Execute External Program correctly updated updated the progress bar of the Uninstall pane the same way as the Install pane does when it executes an external program. 

FAOD, the install external program outputs :InstallPercentComplete x: and uninstall external program :UninstallPercentComplete x: .  The Uninstall pane "Progress Value" is also set to the default <%UninstallPercentComplete%>
.

**Comment by damoncourtney** [comment]
Can you tell me what the properties on your action are set to?  Let me make sure you have things setup properly before I dig any deeper.

**Comment by ams001** [comment]
The setting are:

Clear Progressive Widget: Yes
Execute As Root: Yes
Execute In Console: Yes
Include strerr: No
Program Command Line: <%InstallDir%>/host/bin/creep_uninstall
Progressive Output Widget:
Result Virtual Text: ExternalProgramResult
Show Progressive Output: Yes
Status Virtual Text: ExternalProgramStatus
Wait for Program to Finish Running: Yes
Watch Progressive Output: Yes
Watch Regular Expression: ^:([^ ]+) (.*):$
Watch Virtual Text: Status
Working Directory: <%Temp%>

For the Uninstall pane:
Progress Value: <%UninstallPercentComplete%>

These properties are almost identically equivalent (apart from the obvious <%UninstallPercentComplete%> etc) to a corresponding "Execute External Program" I have in my Install actions which does the right thing.

**Comment by damoncourtney** [comment]
What is the creep_uninstall that it is executing?  Is that a program of your own making?

**Comment by ams001** [comment]
Yes.  It outputs
:UninstallPercentComple x:
as it does it's work.  I have replaced it also with the following external tcl script (i.e. not Execute Script but as a file test.tcl marked +x and got the same result):

<code><pre>
#!/usr/bin/tclsh
for {set i 0} {$i&lt;100} {incr i +1} {
  puts ":UninstallPercentComplete $i:"
  after 500
}
</pre></code>

**Comment by damoncourtney** [comment]
I know that's just an example, but your example there would work if you flush after each puts.  Add "flush stdout" after the puts, and I think you'll find it works.

In your creep_uninstall, are you flushing the output each time?  Standard IO libraries are going to do a fair bit of buffering for you behind your back, and the installer is never going to see your output lines until the whole thing ends and closes the pipe or exits.

**Comment by ams001** [comment]
Thanks.  Adding the flush makes the tcl example work.  I'll double check that creep_uninstall does a flush and get back to you.

**Comment by ams001** [comment]
It did not :-(   My bad. This is not an IJ bug.  With fflush(stdout); it all works as advertised.  

Thanks very much for the help.
